### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by IzzySoft** [MakinGiants/todayhistory#26]
Whith the development seemlingly having stopped back in 2017, would you at least release a new version with the changes you've made since the first release? Or is this project "gone"?

**Comment by danielgomezrico** [comment]
@IzzySoft what do you need?

**Comment by IzzySoft** [comment]
@caipivara I was just wondering if the project is still maintained. To speak figuratively: no good idea riding a "dead horse" if one knows that beforehand :wink:

**Comment by danielgomezrico** [comment]
@IzzySoft there are no deadline for updating this for the moment, so be patient or it will be cool if you send a PR updating the things you want to update 👍

**Comment by IzzySoft** [comment]
No worries. But not being an Android dev, I unfortunately cannot support you with PRs. What I do (and that caused my question) is making Open-Source apps easier accessible outside of Playstore. For your app, e.g. see [here](https://apt.izzysoft.de/fdroid/index/apk/com.makingiants.todayhistory) (the "tracking mark" is caused by Crashlytics). If an app is no longer maintained, I point that out to the users so they are aware of it. No such mark for your app, of course :smiley:

**Comment by IzzySoft** [comment]
@danielgomezrico being patient as requested, I delayed my heads-up for 3 years now (I'm a good boy, aren't I? :see_no_evil:) So I just wonder, is TodayHistory still maintained/developed? No commits for almost 5 years now. Not complaining, just asking :smiley:

**Comment by danielgomezrico** [comment]
@IzzySoft nope, this is not been mantained, what do you need?

**Comment by IzzySoft** [comment]
@danielgomezrico see the link in my comment from 2019-02-15: your app is listed in my repo, and I like my users to know before they decide for an app if it will still be supported and see updates. So I'll just put a corresponding note now. As long as the app is still working, it's fine (no need to fix what is not broken :wink:). I've also disabled update checks – so should you decide to release a new version, a short note would be very welcome!

Thanks a lot!

**Comment by danielgomezrico** [comment]
This app is not published anywhere, it's just a sample repo, so that's why I'm asking you, I will update the README to make that clear

**Comment by IzzySoft** [comment]
No prob – but in case you missed the link: [here's your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.makingiants.todayhistory), where it is listed since 2016-05-11 :wink:

**Comment by danielgomezrico** [comment]
Whats that site? I dont know why this app is listed there

**Comment by IzzySoft** [comment]
It's an F-Droid repo run by me (and quite popular among F-Droid users). As F-Droid is about (F)ree (as in "libre") An(droid) apps, my repo holds apps that for some reason did not make it to [F-Droid.org](https://f-droid.org/) itself – but come open-source, using a free/libre license. So does your app, which comes under the [MIT license](https://github.com/MakinGiants/todayhistory/blob/develop/LICENSE) granting me a.o. the "rights to use, copy, modify, merge, publish, distribute" – which I use to make apps easier accessible to end-users.

So the "why" is because your app's license allows it, and I decided users might like it and thus added it :smile: As for "what": if you need more details, e.g. Wikipedia sums up  [what F-Droid is](https://en.wikipedia.org/wiki/F-Droid) – and [here are some details](https://apt.izzysoft.de/fdroid/index/info) on how my repo operates.

Again, please don't feel "pressed" by this. And if you don't like the idea of your app being present there, I of course respect your choice to have it removed.

**Comment by danielgomezrico** [comment]
I have no issues with that 👍🏻  I will close this issue because we let this clear now

**Comment by IzzySoft** [comment]
Thanks! All the best then, for you and also for your other/current projects. Should you decide to update TodayHistory one day, it's be great if you'd drop me a note when a new release comes up. Only if, no pressure or "high expectations" :wink:
